# Generated by Django 5.0.1 on 2024-02-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default='9b7b2ecfc34911eeb5d400e04ca2aa69', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Логин')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='Эл. почта')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=32, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
