# Generated by Django 5.0.2 on 2024-04-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='e4ec86fef38611ee989f645d868f2c89', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
