# Generated by Django 5.0.2 on 2024-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='9b484660de294a729bcb7d4625c9e66b', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
