# Generated by Django 5.0.2 on 2024-04-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
