# Generated by Django 5.0.2 on 2024-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default='646639a365804963a629548cd057e1d7', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
