# Generated by Django 5.0.2 on 2024-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default='c451757621914c5cbb881a3a1af4a018', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
