# Generated by Django 5.0.2 on 2024-04-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default='9024079ca3ee457992fcc40fb5185f3b', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
