# Generated by Django 5.0.2 on 2024-04-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default='c393baff7f374e3fb0b1db4f0eecbdb5', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
