# Generated by Django 5.0.2 on 2024-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default='c70df7e61a084f35bb5a1376d2c79a34', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
