# Generated by Django 5.0.2 on 2024-04-07 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default='3a713c7ff0db412b8cfbe38b37a8e5d4', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
