# Generated by Django 5.0.2 on 2024-04-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default='b7f94e7e906b4de6b95f793ba5dd41a4', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
