# Generated by Django 5.0.2 on 2024-04-12 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_lesson_alter_course_options_alter_course_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='link',
        ),
        migrations.RemoveField(
            model_name='file',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='student',
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='accept_after_closing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='closing_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='attached_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='course.file'),
        ),
        migrations.AddField(
            model_name='solution',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AlterField(
            model_name='course',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observer_of_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owner_of_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_of_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teacher_of_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='user_query',
            field=models.ManyToManyField(blank=True, related_name='in_user_query_of_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='solutions',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField(blank=True, max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='solutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='course.solution'),
        ),
    ]
