# Generated by Django 5.0.2 on 2024-04-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_file_link_remove_file_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='attached_links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='course.link'),
        ),
    ]
