# Generated by Django 5.0.2 on 2024-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_solution_attached_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
