# Generated by Django 5.0.2 on 2024-04-13 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_task_options_alter_task_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='attached_files',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='attached_links',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='lesson',
        ),
        migrations.AddField(
            model_name='file',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='course.solution'),
        ),
        migrations.AddField(
            model_name='link',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_links', to='course.solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='course.task'),
        ),
        migrations.AddField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
