# Generated by Django 5.0.2 on 2024-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_solution_attached_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='grade',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='higher_grade',
            field=models.IntegerField(default=5),
        ),
    ]
